version: "3"
services:


  postgres:
    networks:
        - postgres-network
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
  pgadmin4:
    networks:
        - postgres-network
    image: dpage/pgadmin4
    depends_on:
        - postgres
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=junior.zilles@compasso.com.br
      - PGADMIN_DEFAULT_PASSWORD=postgres
    links:
      - "postgres:database"

  app:
    container_name: api-svc
    build: .
    ports:
        - "3000:3000"
    environment:
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: postgres
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_DATABASE: compassolisa
      TYPEORM_PORT: 5432
      TYPEORM_ENTITIES: src/**/*.entity.ts
      TYPEORM_ENTITIES_DIR: src/api/entities
      TYPEORM_MIGRATIONS: src/migrations/**/*.ts
      TYPEORM_MIGRATIONS_DIR: src/migrations
      NODE_ENV: prod
      PORT: 3000
    entrypoint:
      - npm
      - run
      - start
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - postgres-network
volumes:
  reserved: 

networks:
    postgres-network:
       driver: bridge